services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  model:
    build: .
    container_name: model_app
    ports:
      - "8080:8080"
    volumes:
      - ./logging.log:/app/logging.log
volumes:
  postgres_data: